"use client";
import { useState, useRef } from "react";
import { useVoiceInput } from "../_lib/useVoiceInput";
import { useImageCapture } from "../_lib/useImageCapture";

const C = {
  bg: "#f4f1ea", surface: "#ffffff", chrome: "#2c3528", gold: "#c49b2a",
  goldLight: "rgba(196,155,42,0.12)", goldGlow: "rgba(196,155,42,0.25)",
  forest: "#2c3528", green: "#4a6540", border: "#d6d1c4", borderLight: "#e8e3d9",
  text: "#2c3528", textMuted: "#7a7462", danger: "#c0392b",
  dangerBg: "rgba(192,57,43,0.08)", dangerGlow: "rgba(192,57,43,0.3)",
};

const SEVERITY_COLORS = {
  Low: { bg: "#EBF5FB", text: "#2980B9", border: "#AED6F1" },
  Medium: { bg: "#FEF9E7", text: "#F39C12", border: "#F9E79F" },
  High: { bg: "#FDEDEC", text: "#E74C3C", border: "#F5B7B1" },
  Critical: { bg: "#F5B7B1", text: "#922B21", border: "#E74C3C" },
};

export default function IncidentReportPage() {
  const voice = useVoiceInput({ lang: "en-US" });
  const image = useImageCapture();
  const [report, setReport] = useState(null);
  const [processing, setProcessing] = useState(false);
  const [error, setError] = useState("");
  const reportRef = useRef(null);

  // Get query params for pre-fill from asset pages
  const params = typeof window !== "undefined" ? new URLSearchParams(window.location.search) : new URLSearchParams();
  const prefillLocation = params.get("location") || "";
  const prefillEquipment = params.get("equipment") || "";

  const generateReport = async () => {
    if (!voice.transcript.trim()) {
      setError("Please describe the incident first.");
      return;
    }
    setProcessing(true);
    setError("");
    setReport(null);

    try {
      const res = await fetch("/api/incident-report", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          transcript: voice.transcript.trim(),
          imageBlock: image.contentBlock || undefined,
          location: prefillLocation,
          equipment: prefillEquipment,
        }),
      });
      const data = await res.json();
      if (data.error) throw new Error(data.error);
      setReport(data.report);
      setTimeout(() => reportRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }), 200);
    } catch (err) {
      setError(err.message);
    } finally {
      setProcessing(false);
    }
  };

  const downloadReport = () => {
    if (!report) return;
    const md = `# INCIDENT REPORT: ${report.title}

**Date:** ${report.date}
**Time:** ${report.time}
**Location:** ${report.location}
**Severity:** ${report.severity}
**OSHA Recordable:** ${report.osha_recordable ? "Yes" : "No"}
**Area Status:** ${report.area_status}

---

## Description
${report.description}

## Injuries
${report.injuries}

## Equipment Involved
${report.equipment_involved}

${report.personnel_involved?.length ? `## Personnel Involved\n${report.personnel_involved.map(p => `- ${p}`).join("\n")}` : ""}

## Immediate Actions Taken
${report.immediate_actions.map(a => `- ${a}`).join("\n")}

## Root Cause Analysis
${report.root_cause || "Pending investigation"}

## Corrective Actions
${report.corrective_actions.map(a => `- ${a}`).join("\n")}

## Follow-Up Required
${report.followup_required.map(f => `- [ ] ${f}`).join("\n")}

---
*Generated by RHONDA on ${new Date().toLocaleDateString()}. Review and approve before filing.*`;

    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `Incident_Report_${report.title.replace(/[^a-zA-Z0-9]/g, "_")}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const formatTime = (s) => `${Math.floor(s / 60)}:${String(s % 60).padStart(2, "0")}`;
  const displayTranscript = voice.transcript + (voice.interimText ? (voice.transcript ? " " : "") + voice.interimText : "");

  return (
    <div style={{ minHeight: "100vh", background: C.bg, fontFamily: "'Outfit', system-ui, sans-serif" }}>
      {/* Header */}
      <div style={{ background: C.danger, padding: "16px 32px", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
          <div style={{ width: 36, height: 36, borderRadius: 8, background: "#fff", display: "flex", alignItems: "center", justifyContent: "center" }}>
            <span style={{ fontSize: 18, fontWeight: 700, color: C.danger }}>!</span>
          </div>
          <div>
            <div style={{ color: "#fff", fontSize: 16, fontWeight: 700, letterSpacing: 0.5 }}>INCIDENT REPORT</div>
            <div style={{ color: "rgba(255,255,255,0.7)", fontSize: 11 }}>Powered by RHONDA</div>
          </div>
        </div>
        <a href="/sunshine" style={{ color: "#fff", fontSize: 12, textDecoration: "none", opacity: 0.8 }}>Back to RHONDA</a>
      </div>

      {prefillLocation && (
        <div style={{ background: C.dangerBg, padding: "10px 32px", fontSize: 12, color: C.danger, fontWeight: 600, display: "flex", alignItems: "center", gap: 8 }}>
          <span>Pre-filled:</span>
          <span style={{ fontWeight: 400 }}>{prefillEquipment} — {prefillLocation}</span>
        </div>
      )}

      <div style={{ maxWidth: 700, margin: "0 auto", padding: "32px 24px" }}>
        {!report && (
          <>
            <div style={{ textAlign: "center", marginBottom: 32 }}>
              <h1 style={{ fontSize: 28, fontWeight: 700, color: C.forest, margin: 0 }}>Report an Incident</h1>
              <p style={{ fontSize: 14, color: C.textMuted, marginTop: 6 }}>Speak or type what happened. RHONDA generates the full report.</p>
            </div>

            {/* Big Record Button */}
            <div style={{ background: C.surface, borderRadius: 16, border: `1px solid ${voice.isRecording ? C.danger : C.border}`, boxShadow: voice.isRecording ? `0 0 24px ${C.dangerGlow}` : "0 2px 8px rgba(0,0,0,0.04)", padding: 32, marginBottom: 24, textAlign: "center", transition: "all 0.3s" }}>
              {voice.supported && (
                <button onClick={voice.isRecording ? voice.stopRecording : voice.startRecording}
                  style={{ width: 120, height: 120, borderRadius: "50%", border: "none", background: C.danger, cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", margin: "0 auto 16px", transition: "all 0.3s", boxShadow: voice.isRecording ? `0 0 0 10px ${C.dangerBg}, 0 0 40px ${C.dangerGlow}` : `0 4px 20px ${C.dangerGlow}`, animation: voice.isRecording ? "pulse 1.5s ease-in-out infinite" : "none" }}>
                  {voice.isRecording ? (
                    <div style={{ width: 32, height: 32, borderRadius: 4, background: "#fff" }} />
                  ) : (
                    <svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                      <rect x="9" y="2" width="6" height="11" rx="3" /><path d="M5 10a7 7 0 0 0 14 0" /><line x1="12" y1="17" x2="12" y2="21" /><line x1="8" y1="21" x2="16" y2="21" />
                    </svg>
                  )}
                </button>
              )}
              {voice.isRecording && (
                <div style={{ fontSize: 16, color: C.danger, fontWeight: 700, marginBottom: 8, display: "flex", alignItems: "center", justifyContent: "center", gap: 8 }}>
                  <div style={{ width: 10, height: 10, borderRadius: "50%", background: C.danger, animation: "pulse 1s infinite" }} />
                  Recording — {formatTime(voice.recordingTime)}
                </div>
              )}
              {!voice.isRecording && !voice.transcript && (
                <p style={{ color: C.textMuted, fontSize: 14, margin: 0 }}>Tap to describe what happened. Hands-free.</p>
              )}

              {(voice.transcript || voice.interimText || !voice.supported) && (
                <div style={{ marginTop: 20, textAlign: "left" }}>
                  <textarea value={displayTranscript} onChange={e => voice.setTranscript(e.target.value)}
                    placeholder="Or type: 'Chemical spill in bay 3, about two gallons, nobody hurt but we need to rope off the area...'"
                    rows={4}
                    style={{ width: "100%", padding: 14, borderRadius: 10, border: `1px solid ${C.borderLight}`, background: C.bg, fontSize: 14, lineHeight: 1.6, color: C.text, fontFamily: "inherit", resize: "vertical", outline: "none", boxSizing: "border-box" }}
                  />
                </div>
              )}
            </div>

            {/* Optional photo */}
            <div style={{ background: C.surface, borderRadius: 12, border: `1px solid ${C.border}`, padding: 20, marginBottom: 24 }}>
              <div style={{ fontSize: 12, fontWeight: 600, color: C.textMuted, textTransform: "uppercase", letterSpacing: 1, marginBottom: 12 }}>
                Photo (optional)
              </div>
              {image.preview ? (
                <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
                  <img src={image.preview} alt="Incident" style={{ width: 80, height: 80, objectFit: "cover", borderRadius: 8, border: `1px solid ${C.borderLight}` }} />
                  <button onClick={image.clear} style={{ fontSize: 12, color: C.danger, background: "none", border: "none", cursor: "pointer", fontFamily: "inherit" }}>Remove</button>
                </div>
              ) : (
                <div style={{ display: "flex", gap: 8 }}>
                  <button onClick={() => image.captureImage({ camera: true })}
                    style={{ padding: "8px 16px", borderRadius: 8, border: `1px solid ${C.border}`, background: C.bg, color: C.textMuted, fontSize: 12, fontWeight: 500, cursor: "pointer", fontFamily: "inherit" }}>
                    Take Photo
                  </button>
                  <button onClick={() => image.captureImage()}
                    style={{ padding: "8px 16px", borderRadius: 8, border: `1px solid ${C.border}`, background: C.bg, color: C.textMuted, fontSize: 12, fontWeight: 500, cursor: "pointer", fontFamily: "inherit" }}>
                    Upload
                  </button>
                </div>
              )}
            </div>

            {/* Errors */}
            {(error || voice.error) && (
              <div style={{ padding: "12px 16px", borderRadius: 8, background: C.dangerBg, color: C.danger, fontSize: 13, marginBottom: 24 }}>{error || voice.error}</div>
            )}

            {/* Generate button */}
            <div style={{ textAlign: "center" }}>
              <button onClick={generateReport} disabled={processing || !voice.transcript.trim()}
                style={{ padding: "14px 40px", borderRadius: 12, border: "none", background: processing || !voice.transcript.trim() ? C.border : C.danger, color: processing || !voice.transcript.trim() ? C.textMuted : "#fff", fontSize: 16, fontWeight: 700, cursor: processing || !voice.transcript.trim() ? "not-allowed" : "pointer", fontFamily: "inherit", display: "inline-flex", alignItems: "center", gap: 8 }}>
                {processing ? (
                  <><span style={{ display: "inline-block", width: 18, height: 18, border: "2px solid rgba(255,255,255,0.3)", borderTop: "2px solid #fff", borderRadius: "50%", animation: "spin 0.8s linear infinite" }} />Generating Report...</>
                ) : "Generate Incident Report"}
              </button>
            </div>
          </>
        )}

        {/* Generated Report */}
        {report && (
          <div ref={reportRef} style={{ animation: "fadeIn 0.4s ease" }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 }}>
              <h2 style={{ fontSize: 22, fontWeight: 700, color: C.forest, margin: 0 }}>Incident Report</h2>
              <div style={{ display: "flex", gap: 8 }}>
                <button onClick={() => { setReport(null); voice.resetTranscript(); image.clear(); }}
                  style={{ padding: "6px 14px", borderRadius: 6, border: `1px solid ${C.border}`, background: C.surface, color: C.textMuted, fontSize: 12, fontWeight: 500, cursor: "pointer", fontFamily: "inherit" }}>New Report</button>
                <button onClick={downloadReport}
                  style={{ padding: "6px 14px", borderRadius: 6, border: `1px solid ${C.danger}`, background: C.dangerBg, color: C.danger, fontSize: 12, fontWeight: 600, cursor: "pointer", fontFamily: "inherit" }}>Download</button>
              </div>
            </div>

            <div style={{ background: C.surface, borderRadius: 16, border: `1px solid ${C.border}`, overflow: "hidden" }}>
              {/* Title bar */}
              <div style={{ background: SEVERITY_COLORS[report.severity]?.bg || C.bg, padding: "16px 24px", borderBottom: `2px solid ${SEVERITY_COLORS[report.severity]?.border || C.border}` }}>
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                  <h3 style={{ margin: 0, fontSize: 18, fontWeight: 700, color: C.forest }}>{report.title}</h3>
                  <span style={{ padding: "4px 12px", borderRadius: 20, fontWeight: 700, fontSize: 12, background: SEVERITY_COLORS[report.severity]?.bg, color: SEVERITY_COLORS[report.severity]?.text, border: `1px solid ${SEVERITY_COLORS[report.severity]?.border}` }}>
                    {report.severity}
                  </span>
                </div>
                <div style={{ display: "flex", gap: 16, marginTop: 8, fontSize: 12, color: C.textMuted }}>
                  <span>{report.date} at {report.time}</span>
                  <span>|</span>
                  <span>{report.location}</span>
                  {report.osha_recordable && <span style={{ color: C.danger, fontWeight: 700 }}>OSHA RECORDABLE</span>}
                </div>
              </div>

              {/* Report body */}
              <div style={{ padding: "20px 24px" }}>
                <Section title="Description" content={report.description} />
                <Section title="Injuries" content={report.injuries} />
                <Section title="Equipment Involved" content={report.equipment_involved} />
                {report.personnel_involved?.length > 0 && (
                  <Section title="Personnel Involved" content={report.personnel_involved.map(p => `- ${p}`).join("\n")} />
                )}
                <Section title="Area Status" content={report.area_status} />
                <ListSection title="Immediate Actions Taken" items={report.immediate_actions} color={C.green} />
                {report.root_cause && <Section title="Root Cause Analysis" content={report.root_cause} />}
                <ListSection title="Corrective Actions" items={report.corrective_actions} color={C.gold} />
                <ListSection title="Follow-Up Required" items={report.followup_required} color={C.danger} checkbox />
              </div>

              {/* Footer */}
              <div style={{ borderTop: `1px solid ${C.borderLight}`, padding: "12px 24px", background: C.bg, fontSize: 11, color: C.textMuted }}>
                Generated by RHONDA on {new Date().toLocaleDateString()} — Review and approve before filing
              </div>
            </div>
          </div>
        )}
      </div>

      <style>{`
        @keyframes pulse { 0%,100% { opacity:1 } 50% { opacity:0.5 } }
        @keyframes spin { to { transform: rotate(360deg); } }
        @keyframes fadeIn { from { opacity:0; transform:translateY(8px); } to { opacity:1; transform:translateY(0); } }
      `}</style>
    </div>
  );
}

function Section({ title, content }) {
  return (
    <div style={{ marginBottom: 16 }}>
      <div style={{ fontSize: 11, fontWeight: 700, color: "#c49b2a", letterSpacing: "0.1em", textTransform: "uppercase", marginBottom: 4 }}>{title}</div>
      <div style={{ fontSize: 13, lineHeight: 1.6, color: "#2c3528", whiteSpace: "pre-wrap" }}>{content}</div>
    </div>
  );
}

function ListSection({ title, items, color = "#2c3528", checkbox = false }) {
  if (!items?.length) return null;
  return (
    <div style={{ marginBottom: 16 }}>
      <div style={{ fontSize: 11, fontWeight: 700, color: "#c49b2a", letterSpacing: "0.1em", textTransform: "uppercase", marginBottom: 6 }}>{title}</div>
      {items.map((item, i) => (
        <div key={i} style={{ display: "flex", alignItems: "flex-start", gap: 8, marginBottom: 4, fontSize: 13, color: "#2c3528" }}>
          {checkbox ? (
            <input type="checkbox" style={{ marginTop: 3, accentColor: color }} />
          ) : (
            <div style={{ width: 6, height: 6, borderRadius: "50%", background: color, marginTop: 6, flexShrink: 0 }} />
          )}
          <span>{item}</span>
        </div>
      ))}
    </div>
  );
}
