export async function POST(request) {
  const { transcript, companyName, department, fromInterview } = await request.json();

  if (!transcript || transcript.trim().length < 20) {
    return Response.json(
      { error: "Transcript too short. Please describe the procedure in more detail." },
      { status: 400 }
    );
  }

  const sourceDesc = fromInterview
    ? "A worker has just been interviewed by RHONDA about their job. The transcript below is a back-and-forth conversation where RHONDA asked questions and the worker explained their procedures, skills, and standards. Extract ALL procedures discussed and convert them into professional SOPs."
    : "A worker has just described a procedure by speaking into their phone. Your job is to convert their spoken description into a professional, formatted SOP document.";

  const systemPrompt = `You are RHONDA, an expert SOP (Standard Operating Procedure) generator for ${companyName || "a manufacturing company"}.

${sourceDesc}

IMPORTANT RULES:
- Extract the procedure name from what they described
- Number every step clearly
- Flag any safety warnings with ⚠️
- Add a "Required PPE" section if any protective equipment is mentioned or implied
- Add a "Tools & Materials" section listing anything referenced
- If the worker mentions frequencies (daily, weekly, per batch), note them
- Use simple, direct language a floor worker can follow
- If something is ambiguous, note it as "[VERIFY]" so a supervisor can confirm
- End with a checklist version of the steps for daily use

OUTPUT FORMAT (use this exact markdown structure):

# SOP: [Procedure Name]
**Department:** ${department || "[Department]"}
**Effective Date:** [Today's date]
**Version:** 1.0 — Generated from worker interview

---

## Purpose
[One sentence describing why this procedure exists]

## Scope
[Who this applies to and when]

## Required PPE
- [List items, or "None required" if not applicable]

## Tools & Materials
- [List items needed]

## Procedure

### Step 1: [Step Title]
[Clear instruction in 1-2 sentences]

### Step 2: [Step Title]
[Clear instruction in 1-2 sentences]

[Continue for all steps...]

## Safety Warnings
⚠️ [List any safety concerns mentioned or implied]

## Quality Checkpoints
- [ ] [Checkpoint derived from the procedure]
- [ ] [Checkpoint derived from the procedure]

---

## Daily Checklist Version

- [ ] Step 1: [Brief version]
- [ ] Step 2: [Brief version]
[All steps as checkboxes]

---
*Generated by RHONDA from worker interview on [today's date]. Review and approve before use.*`;

  const userContent = fromInterview
    ? `Here is a Teach RHONDA interview transcript. Extract the procedures discussed and convert into professional SOP(s):\n\n${transcript}`
    : `Here is a worker's spoken description of a procedure. Convert it into a professional SOP:\n\n"${transcript}"`;

  const response = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": process.env.ANTHROPIC_API_KEY,
      "anthropic-version": "2023-06-01",
      "anthropic-beta": "prompt-caching-2024-07-31",
    },
    body: JSON.stringify({
      model: "claude-sonnet-4-6",
      max_tokens: 4096,
      system: [{ type: "text", text: systemPrompt, cache_control: { type: "ephemeral" } }],
      messages: [
        {
          role: "user",
          content: userContent,
        },
      ],
    }),
  });

  const data = await response.json();
  return Response.json(data, { status: response.status });
}
